name: hola

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev

      - name: Installing Most the tools 
        run: |
           GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
           GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
           GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
           GO111MODULE=on go get -v github.com/projectdiscovery/notify/cmd/notify@v0.0.2
        shell: bash

      - name: Downloading Nuclei Templates
        run: |
          nuclei -update-templates
        shell: bash

      - name: Running VA with Hola
        run: |
          subfinder -dL hosts.txt | httpx | nuclei -stats -s low,medium,high,critical -c 50 -rl 300 -nc | notify -slack -slack-webhook-url  ${{ secrets.SLACK_TOKEN }}
        shell: bash
